In [ ]:
print("hello world")

hello world


In [ ]:
print("i am a good girl \n and she is a bad girl")

i am a good girl 
 and she is a bad girl


In [ ]:
print(420*31)

13020


In [ ]:
print("hey", 22 , 12, sep="~", end="099345\n")

hey~22~12099345


In [ ]:
a= 16*3
b= "string"
a1= "string calculatar"
print(a)
print(b)
print("the type of a1 is",type(a))
print("the type of a is",type(a1))
print("the type of b is",type(b))




48
string
the type of a1 is <class 'int'>
the type of a is <class 'str'>
the type of b is <class 'str'>


In [ ]:
print("hello world")

hello world


In [ ]:
#PYTHON COMMENTS
print(419*31)



12989


data **type**

In [ ]:
x =2
print(x)
print(type(x))

2
<class 'int'>


In [ ]:
y =4.5
print(y)
print(type(y))

4.5
<class 'float'>


In [ ]:
z = 2+5j
print(z)
print(type(z))

(2+5j)
<class 'complex'>


In [ ]:
a = "this is the day 1 of python class"
print(a)
print(type(a))

this is the day 1 of python class
<class 'str'>


In [ ]:
b =  [1,2,3,4,5,6,7,8,9,10]
print(b)
print(type(b))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'list'>


In [ ]:
c = (1,2,3,3,3,4,4,4,4,4)
print(c)
print(type(c))

(1, 2, 3, 3, 3, 4, 4, 4, 4, 4)
<class 'tuple'>


In [ ]:
%whos

Variable   Type       Data/Info
-------------------------------
a          str        this is the day 1 of python class
b          list       n=10
c          tuple      n=10
x          int        2
y          float      4.5
z          complex    (2+5j)


**OPERATORS IN** **PYTHON**

In [ ]:
a = 5
b = 4
print(a+b)

9


In [ ]:
a = 3
b = 3.2
print(a+b)

6.2


In [ ]:
a = 3+2j
b = 3
print(a+b)

(6+2j)


In [ ]:
a = "Hello"
b = "students"
print(a+" "+b)

Hello students


In [ ]:
a = 15
b = 10
print(a-b)

5


In [ ]:
a = 2.3
b = 1.3
print(a-b)

0.9999999999999998


**multiply**

In [ ]:
a= 45
b= 45
print(a*b)

2025


In [ ]:
a= 23.23
b= 2323
print(a*b)

53963.29


**Divison**

In [ ]:
a= 23
b= 2
print(a/b)

11.5


**Modules**

In [ ]:
a =23
b= 3
print(a%b)

2


In [ ]:
a= 12
b= 3
print(a%b)

0


**EXPONENT**

In [ ]:
a = 41256789
b = 2
print(a**55)

71162028433520217717099884851404495326786614148274137562533191244754226421072922193229393035406290047490322006127486170528820460414671897074184746917638236810663780872933871199771053029074871072046645088603300420278272474373361352870797685329285463690039885441075398107839063255747535400015566353549647882767414182717586010912021318113386679928289227315380064286145450539958069165193638416244911434618495833200180049949


In [ ]:
a = ((789*78)+(78.256/45)-(45*4)+(856**57))
print(a)

1.4158087322788437e+167


In [ ]:
a =  True
b= False
print(a and b)

False


In [ ]:
a= True
b= True
print(a and b)

True


In [ ]:
a= False
b= False
print(a and b)

False


In [ ]:
a= False
b=False
print(not(a))

True


In [ ]:
a= True
b= True
print(not(a))

False


In [ ]:
a= ((8922*2852)+(7821*222)-(2566*256)+(8281187))
print(a)

34806097


**DAY 3 BUILT IN FUNCTIONS**

In [ ]:
x= abs(-233.3)
print(x)

233.3


In [ ]:
x= bin(36)
print(x)

0b100100


In [ ]:
y=bin(19)
print(y)

0b10011


**Python bytes function**

In [ ]:
a=bytes(4)
print(a)

b'\x00\x00\x00\x00'


In [ ]:
x=bytes(12)
print(x)

b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'


In [ ]:
a=chr(95)
print(a)

_


In [ ]:
a= complex(3,4.5)
print(a)

(3+4.5j)


In [ ]:
a= complex(4,3)
print(a)

(4+3j)


**String function**

In [ ]:
a= str("23456*67")
print(a)
print(type(a))

23456*67
<class 'str'>


In [ ]:
a= str("54647.2727")
print(a)
print(type(a))

54647.2727
<class 'str'>


**input function**

In [ ]:
a= input("enter your name")
print("Hey",a)
b= input("enter your age")
print("your age is",b)
c=input("enter your gender")
print("your gender is" ,c)
x =input("enter your location")
print("your location is",x)

enter your nameshruit
Hey shruit
enter your age21
your age is 21
enter your genderfemale
your gender is female
enter your locationdelhi
your location is delhi


**CONTROL FLOW STATEMENT**

**#IF CONDITON**

WRITE A PROGRAM TO CALCULATE A PERCENTAGE OF A STUDENT IN THE SUBJECTS MATHS SCIENCE SOCIAL ENGLISH AND HINDI

In [ ]:
x=input("ENTER THE NAME OF STUDENT")
y=int(input("Enter the marks of maths"))
z=int(input("Enter the marks of science"))
a=int(input("Enter the marks of social science"))
b=int(input("Enter the marks of hindi"))
c=int(input("Enter the marks of english"))
n=((y+z+a+b+c)/500)*100
print("the percent scored by shruti is", n)

ENTER THE NAME OF STUDENTshruti
Enter the marks of maths56
Enter the marks of science78
Enter the marks of social science56
Enter the marks of hindi78
Enter the marks of english80
the percent scored by shruti is 69.6


In [ ]:
a=int(input("EN6TER THE PERCENTAGE SCORED BY A STUDENT"))
if a>=90:
  print("A grade")
  if a>=75 and a<90:
    print("b grade")
if a>=65 and a<75:
  print("c garde")


EN6TER THE PERCENTAGE SCORED BY A STUDENT70
c garde


**if else statement**

**Write a number to display hello ifn numeber entered by user is a multiple of 5 else print bye**

In [ ]:
a= int(input("Enter the number"))

if a%5==0:
  print("Hello")
else:
  print("bye")

Enter the number29
bye


In [ ]:
a=int(input("Enter the number"))
if a>0:
  print("positive number")
else:
  print("negative number")

Enter the number-2
negative number


** if elif else**

In [ ]:
city= input("enter the city").strip()
if city== "Delhi":
  print("the monument in Delhi is red fort")
elif city =="Agra":
  print("the monument in Agra is Taj mahal")
elif city== "jaipur":
  print("the  monument  in jaipur is jalmahal")
elif city=="Orisaa":
  print("the monument in orissa is konak temple")
elif city=="hyderabad":
  print("the monument in hyderabad is charminar")
else:
  print("record not found")

**Concept of loops
while loop
program to display number from 1 to 5**

In [ ]:
i = 1
n = 10
while i<=n:
  print(i)
  i=i+1

In [ ]:


x = int(input("enter the value"))
i = 1
while i<=10:
  print(x*i)
  i=i+1
print("this is the multiple table")

1
2
3
4
5
6
7
8
9
10
this is the multiple table


**using else statement in the while loop**

In [ ]:
count=0
while(count<25):
 count=count+1
 print("hello student")
else:
  print("this is the else block")

hello student
hello student
hello student
hello student
hello student
hello student
hello student
hello student
hello student
hello student
hello student
hello student
hello student
hello student
hello student
hello student
hello student
hello student
hello student
hello student
hello student
hello student
hello student
hello student
hello student
this is the else block


**for loop**

In [ ]:
fruits=["apple","banana","cherry"]
for x in fruits:
  print(x)

apple
banana
cherry


**looping through a string**

In [ ]:
for x in "banana":
  print(x)

b
a
n
a
n
a


In [ ]:
for x in range(3,50):
  print(x)

3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49


**creating a user defined function**

In [ ]:
def my_function():
  print("hello class")
  print("this is the function")
my_function()


hello class
this is the function


In [ ]:
 def contact():
  print("contact details of the school")
  print("Delhi public school")
  print("Bangalore karnataka")
  print("345676542")
  print("dps.contact@gmail.com")

In [ ]:
for i in range(4):
  a=input("Name of the student")
  b=int(input("enter the marks of maths"))
  c= int(input("enter the marks of science"))
  d=int(input("enter the marks of social science"))
  print()
  contact()


contact details of the school
Delhi public school
Bangalore karnataka
345676542
dps.contact@gmail.com

contact details of the school
Delhi public school
Bangalore karnataka
345676542
dps.contact@gmail.com


**argument**

In [ ]:
def my_function(fname):
  print(fname + " verma")



In [ ]:
my_function("shruti")
my_function("priya")

shruti verma
priya verma


**write a program to calculate the elecetricity bill**
if 500 unit used - pay rs 5 for each unit
if 700 unit used - pay rs 10 each unit
if 1000 unit used - pay rs 15 each unit
if more than 1000 unit used -  pay rs 20 each unit

In [ ]:
def electricity_bill(n):
  if n<=500:
     print("your bill is rs ",n*5)
  elif n<500 and n<1000:
    print("your bill is rs ",n*10)
  elif n<700 and n<1000:
    print("your bill is rs ",n*15)
  elif n>1000:
    print("your bill is rs ",n*20)


In [ ]:
for i in range(3):
  a= input("Enter the name of customer")
  n = int(input("enter the unit of you have electricity you have used"))
  electricity_bill(n)

Enter the name of customerhdn
enter the unit of you have electricity you have used1000
Enter the name of customershruti
enter the unit of you have electricity you have used200
your bill is rs  1000
Enter the name of customernjsjkf
enter the unit of you have electricity you have used500
your bill is rs  2500


In [ ]:
def instructions():
  print("last date of paying the bill is 20 april")
  print("after 20 april you need to pay 1000 rs as a fine")
  print("electricity office new delhi")



\

In [ ]:
for i in range(3):
  a= input("Enter the name of customer")
  n= int(input("enter the unit of you have electricity you have used"))
  electricity_bill(n)
  print()
  intructions()



In [ ]:
def medical_store(n):
  if n<=10:
    print(" Your total bill is",n*10)
  elif n<=20:
    print("Your total bill is",n*20)


In [ ]:
for i in range(3):
  a= input("Enter the name of medicine")
  n= int(input("Enter the bill of medicine"))
  medical_store(n)
  print()




Enter the name of medicineparacetamol
Enter the bill of medicine10


NameError: name 'medical_store' is not defined

day 6

string in python

In [ ]:
a ="hello"
print(a)

In [ ]:
b="a data analyst,gathered"
print(b)
print(b(type))

indexing of string

In [ ]:
s = "how's your studies going on?"
print(s[11])
s = "how's your study going on?"
print(s[-2])
s = "how's your study going on?"
print(s[1:5])
s = "how's your study going on?"
print(s[:5])
s = "how's your study going on?"
print(s[1:])
s = "how's your study going on?"
print(s[::-1])

s
n
ow's
how's
ow's your study going on?
?no gniog yduts ruoy s'woh


finding the lenght of functions

In [ ]:
a = "this is our day 7 python class"
print(len(a))

30


In [ ]:
b = "Hi shruti"
print(len(b))

9


upper method

In [ ]:
a = "hello how are you?"
print(a.upper())

HELLO HOW ARE YOU?


lower method

In [ ]:
a = "HELLO STUDENT"
print(a.lower(a))

TypeError: str.lower() takes no arguments (1 given)

Replace function

In [ ]:
a= "hello how are you?"
print(a.replace("hello", "bye"))

bye how are you?


In [ ]:
b= "hello world"
print(b.replace("world","student"))

hello student


finding method

In [ ]:
 a ="python is great"
 b = a.find("i")
 print(b)

7


day 8

list in python

In [ ]:
mylist = ["apple,banana,grapes"]
print(mylist)
print(type(mylist))

['apple,banana,grapes']
<class 'list'>


allow duplicate

In [ ]:
mylist = ["apple","apple" ,"banana","cherry","cherry","grapes"]
print(mylist)


['apple', 'apple', 'banana', 'cherry', 'cherry', 'grapes']


data type

In [ ]:
list1 = ["apple","banana", "grapes","cherry"]
list2 = [23,24,35]
list3 = [True]
list4 = [2.3,34.3,3.4]
print(list1)
print(list2)
print(list3)
print(list4)

['apple', 'banana', 'grapes', 'cherry']
[23, 24, 35]
[True]
[2.3, 34.3, 3.4]


list length

In [ ]:
a = [12,-8,5,7,6,23,"student","hello", "true" , "false"]
print(len(a))

10


In [ ]:
b = [12,34,4,24,24,3,434]
print(len(b))

7


Access items

In [ ]:
thislist = [12,34,3,23,56,678,44,3,4,5,5,663,3,2]
print(thislist[5])

678


In [ ]:
mylist = [12,15,16,17,18,19,20]
print(mylist[5])

19


In [ ]:
mylist = [6,53,8,8,54,5.6,34,35,90,-2]
print(mylist[-5])

5.6


slicing of list

In [ ]:
mylist = [2,4,5,6,7,89,9,0,1,2,3,45,5]
print(mylist[0:6])

[2, 4, 5, 6, 7, 89]


In [ ]:
mylist = [3,6,9,21,24,27,30]
print(mylist[6:-2])

[]


In [ ]:
mylist = [3,4,5,6,7,6,3,2]
print(mylist[0:12:3])

[3, 6, 3]


#change items

In [ ]:
mylist = ["banana","apple","grapes"]
mylist[0] = "strawberry"
print(mylist)

['strawberry', 'apple', 'grapes']


In [ ]:
a = [12,13,14,15,61,171,8,11119]
a[7] = "students"
print(a)

[12, 13, 14, 15, 61, 171, 8, 'students']


In [ ]:
a = [12,13,14,15,16,17]
a[0:1] = ["books" , "pen"]
print(a)

['books', 'pen', 13, 14, 15, 16, 17]


In [ ]:
a = [12,13,14,15,16,17]
a.append(21)
print(a)

[12, 13, 14, 15, 16, 17, 21]


In [ ]:
a = [12,13,14,15,16,17]
a.remove(17)
print(a)

[12, 13, 14, 15, 16]


In [ ]:
a = [12,13,14,15,16,17]
a.reverse()
print(a)


[17, 16, 15, 14, 13, 12]


In [ ]:
a = [12,14,15,6,6,34,1415,35,35,36,728,]
print(len(a))
b = 0
for i in range(11):
  b = b+a[i]
  #i = i+i  #This line was causing an infinite loop.  If you need to increment i, increment it by 1
  print("the sum of a list is ", b)





11
the sum of a list is  12
the sum of a list is  26
the sum of a list is  41
the sum of a list is  47
the sum of a list is  53
the sum of a list is  87
the sum of a list is  1502
the sum of a list is  1537
the sum of a list is  1572
the sum of a list is  1608
the sum of a list is  2336


multiply all the numbers of a list

In [ ]:
a =[1,2,3,4,5,6,7,8,9,10]
b =1
for i in range(10):
    b = b*a[i]
print("the multiply of all the numbers is", b )

the multiply of all the numbers is 3628800


tuples in python

creating a tuple

In [ ]:
my_tuple =(1,2,3)
print(my_tuple)
print(type(my_tuple))

(1, 2, 3)
<class 'tuple'>


mixed data type

In [ ]:
my_tuple =(1,2,"string",3.2,45+4j)
print(my_tuple)
print(type(my_tuple))

(1, 2, 'string', 3.2, (45+4j))
<class 'tuple'>


In [ ]:
my_tuple =()
print(my_tuple)
print(type(my_tuple))

()
<class 'tuple'>


nested tuple

In [ ]:
my_tuple =("data",[1,2,3,4,5],(2,3,4))
print(my_tuple)

('data', [1, 2, 3, 4, 5], (2, 3, 4))


creating a tuple only one item

In [ ]:
var1 = ("hey there",)
print(var1)
print(type(var1))

('hey there',)
<class 'tuple'>


tuple constructer

In [ ]:
a =tuple(("a","b","c"))
print(a)
print(type(a))

('a', 'b', 'c')
<class 'tuple'>


indexing

In [ ]:
a=(32,45,35,6,76,87,9,7,97)
print(a[5])

87


In [ ]:
a=(32,45,35,6,76,87,9,7,97,"hello","student")
print(a[10])

student


In [ ]:
a=(32,45,35,6,76,87,9,7,97,"hello","student")
print(a[-5])

9


slicing

In [ ]:
a=(32,45,35,6,76,87,9,7,97,"hello","student")
print(a[7:10])

(7, 97, 'hello')


In [ ]:
a=(32,45,35,6,76,87,9,7,97,"hello","student")
print(a[::3])

(32, 6, 9, 'hello')


how dcan we reverse tuple in python

In [ ]:
a=(32,45,35,6,76,87,9,7,97,"hello","student")
print(a[::-1])

('student', 'hello', 97, 7, 9, 87, 76, 6, 35, 45, 32)


In [ ]:
t =(1,2,3,4,5,6,7,8)
print(t[::])
print(t[3:])
print(t[:4])
print(t[-2:-5])

(1, 2, 3, 4, 5, 6, 7, 8)
(4, 5, 6, 7, 8)
(1, 2, 3, 4)
()


In [ ]:
t =(1,2,3,4,5,6,7,8)
y = list(t)
y.append(22)
t =tuple(y)
print(t)

(1, 2, 3, 4, 5, 6, 7, 8, 22)


In [ ]:
 t =(1,2,3,4,5,6,7,8)
y = list(t)
y.remove(8)
t =tuple(y)
print(t)

(1, 2, 3, 4, 5, 6, 7)



delete function
```
# This is formatted as code
```



In [ ]:
t =(1,2,3,4,5,6,7,8)
del t
print(t)

NameError: name 't' is not defined

for loop

In [ ]:
thistuple = ("a","V","d")
for a in thistuple:
print(a)

IndentationError: expected an indented block after 'for' statement on line 2 (<ipython-input-45-c6083895d3b4>, line 3)

join two tuple

In [ ]:
tuple1 =("hello","student")
tuple2 =(1,3,2,3)
tuple3 =(tuple1 + tuple2)
print(tuple3)

('hello', 'student', 1, 3, 2, 3)


multiply tuple

```
# This is formatted as code
```



In [ ]:
a ="apple","tamato","data"
b =a*4
print(b)

('apple', 'tamato', 'data', 'apple', 'tamato', 'data', 'apple', 'tamato', 'data', 'apple', 'tamato', 'data')


In [ ]:
t =(1,2,3,4)
print(t*2)

(1, 2, 3, 4, 1, 2, 3, 4)


In [ ]:
t =(1,2,3,4)
print(t*2)

(1, 2, 3, 4, 1, 2, 3, 4)


In [ ]:
t =(1,2,3,4)
print(t+t+t)

(1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4)


In [ ]:
t =(1,2,3,4)
print(t+t)

(1, 2, 3, 4, 1, 2, 3, 4)


In [ ]:
t =(1,2,3,4)
print(len(t))

4


write a program,to take 5 input from the user and store it in a tuple

In [ ]:
t =()
i =0
while i<=5:
  five =int(input("Enter the values please"))
  t = t +(five,)
  i = i+1
  print(t)

(20,)
(20, 12)
(20, 12, 234)
(20, 12, 234, 34)


In [ ]:
creating a dictionary

In [ ]:
a ={
    "ID":"SHRUTI",
    "abc123":"isitdictionary",
    "year":1990
}
print(a)
print(type(a))

In [ ]:
a ={
    "ID":"SHRUTI",
    "abc123":"isitdictionary",
    "year":1990
}
print(a["abc123"])

isitdictionary


In [ ]:
a ={"name":"shruti",
    "age":"21",
    "country":"India"}
a.update({"qualification":"BCA"})
  print(a)


IndentationError: unexpected indent (<ipython-input-11-71a4d00d0d75>, line 5)

In [ ]:
a = {"name":"shruti",
    "age":"21",
    "country":"India"}
    a.pop("age")
    print(a)

IndentationError: unexpected indent (<ipython-input-13-9ffd10cf7d5b>, line 4)

In [ ]:
a {"age":"21"}
del a
print(a)

SyntaxError: invalid syntax (<ipython-input-15-6c79846a762c>, line 1)

In [ ]:
a {"print":"dictinary",
   "age":"21"}
   a.clear()
   print(a)
   print(type(a))

SyntaxError: invalid syntax (<ipython-input-16-e17a28864d45>, line 1)

In [ ]:
dict1 = {1:10,2:10}
dict2 = {3:10,4:10}
dict3 = {4:10,5:10}
dict4 = {}
for d in(dict1,dict2,dict3):dict4.update(d)
print(dict4)

{1: 10, 2: 10, 3: 10, 4: 10, 5: 10}


In [ ]:
dict1 ={1:1}
dict2 = {2:4}
dict3 ={3:9}
dict4 ={4:16}
dict5 ={}
for d in (dict1,dict2,dict3,dict4):dict5.update(d)
print(dict5)

{1: 1, 2: 4, 3: 9, 4: 16}


In [ ]:
d = dict()
for x in range(1,16):
    d[x] = x**2
print(d)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225}


In [ ]:
d = dict()
for x in range(2,21):
  d[x] = x**2
  print(d)

{2: 4}
{2: 4, 3: 9}
{2: 4, 3: 9, 4: 16}
{2: 4, 3: 9, 4: 16, 5: 25}
{2: 4, 3: 9, 4: 16, 5: 25, 6: 36}
{2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49}
{2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}
{2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}
{2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}
{2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121}
{2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144}
{2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169}
{2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196}
{2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225}
{2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225, 16: 256}
{2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225, 16: 256, 

sets

In [ ]:
a = {"animal","cat","dog","tiger"}
print(a)
print(type(a))

{'cat', 'tiger', 'dog', 'animal'}
<class 'set'>


set items are unordered

In [ ]:
a = {"animal","cat","dog","tiger"}
print(a[0])

TypeError: 'set' object is not subscriptable

duplicates are allowed

In [ ]:
a = {"animal","cat","dog","tiger","tiger","animal","cat","dog"}
print(a)


{'cat', 'tiger', 'dog', 'animal'}


true and 1 is considered as a same value

In [ ]:
a = {"animal","cat","dog","tiger","tiger","1", "True" }
print(a)

{'tiger', '1', 'dog', 'animal', 'cat', 'True'}


In [ ]:
get the length of the set

In [ ]:
a = {"animal","cat","dog","dog","tiger","tiger","1", "True","animal"}
print(len(a))

6


In [ ]:
set items #data type

In [ ]:
 x1 ={1,2,3,4}
 x2 ={1.2,3.2,43.3}
 x3 ={"a","b","c"}
 x4 ={True,False}
 print(x1)
 print(x2)
 print(x3)
 print(x4)

{1, 2, 3, 4}
{1.2, 3.2, 43.3}
{'a', 'b', 'c'}
{False, True}


In [ ]:
n ={1,2,3,3.4,6+5j},"apple","mango"
print(n)
print(type(n))

({1, 2, 3, 3.4, (6+5j)}, 'apple', 'mango')
<class 'tuple'>


In [ ]:
x ={[1,2,3,4,4,5,6,]}
print(x)

TypeError: unhashable type: 'list'

In [ ]:
a ={{"a:1","b:2","c:3"}}
print(a)

TypeError: unhashable type: 'set'

the set constructer

In [ ]:
thisset =({"alpha","beta","gama"})
print(thisset)
print(type(thisset))

{'gama', 'beta', 'alpha'}
<class 'set'>


creating empty set

In [ ]:
a ={}
print(a)
print(type(a))

{}
<class 'dict'>


In [ ]:
a =set()
print(a)
print(type(a))

set()
<class 'set'>


access items

In [ ]:
a = {"a","c","b"}
for x in a:
  print(a)


{'a', 'c', 'b'}
{'a', 'c', 'b'}
{'a', 'c', 'b'}


check if items is present in the set

In [ ]:
a ={"data","anaylist","google","microsoft"}
print("code" in a)

False


In [ ]:
a ={"data","anaylist","google","microsoft"}
print("data" in a)

True


add items

In [ ]:
b = {"a","b","c","d"}
b.add(100)
print(b)

{'a', 100, 'b', 'c', 'd'}


In [ ]:
a ={100,200,300,400,500}
v = {"data","code","python"}

a.update(v)
print(a)

{400, 'code', 100, 500, 200, 'data', 300, 'python'}


remove set items

In [ ]:
a ={100,200,300,400,500}
a.remove(100)
print(a)

{400, 500, 200, 300}


In [ ]:
b ={100,200,300,400,500}
x = b.pop()
print(b)

{100, 500, 200, 300}


In [ ]:
b ={100,200,300,400,500}
del b
print(b)

NameError: name 'b' is not defined

join  two sets

In [ ]:
b = {100,200,300,400,500}
y = {"code","error","run"}
x = b.union(y)
print(x)

{400, 'code', 100, 500, 'run', 'error', 200, 300}


write a python progam to find max and min values

In [ ]:
setn = {10,20,30,402,4,5,67,5,5,4,4,5,5,7,7,8}
print("original set elements")
print(setn)
print("Maximun value of the set is")
print(max(setn))
print("Minimum value of the set is")
print(min(setn))


original set elements
{67, 4, 5, 7, 8, 10, 402, 20, 30}
Maximun value of the set is
402
Minimum value of the set is
4


return a new set of identical items from two sets

In [ ]:
set ={10,20,30,40,50,60,70,80,90}
set2 = {10,20,304,50,50,60,70,80,90}
print(set.intersection(set2))

{70, 10, 80, 50, 20, 90, 60}


import numpy as np

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1


In [ ]:
arr = np.array((1,2,3,4,5,6))
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1


dimensions in array

In [ ]:
import numpy as np

In [ ]:
arr = np.array(40)
print(type(arr))
print(arr.ndim)


<class 'numpy.ndarray'>
0


1 dimensions array


In [ ]:
arr = np.array([1,3,2,3,4,2,4,5,67,75,4,])
print(arr)
print(type(arr))
print(arr.ndim)


[ 1  3  2  3  4  2  4  5 67 75  4]
<class 'numpy.ndarray'>
1


In [ ]:
arr = np.array([[1,3,2],[4,5,67]])
print(arr)
print(type(arr))
print(arr.ndim)

[[ 1  3  2]
 [ 4  5 67]]
<class 'numpy.ndarray'>
2


In [ ]:
arr = np.array([[1,2,3,4,5.4],[1,2,3,4,5]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1.  2.  3.  4.  5.4]
 [1.  2.  3.  4.  5. ]]
<class 'numpy.ndarray'>
2


In [ ]:
import numpy as np

In [ ]:
arr = np.array([[[1,2,3],[6,7,8],[11,12,13]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[ 1  2  3]
  [ 6  7  8]
  [11 12 13]]]
<class 'numpy.ndarray'>
3


higher dimensions array
an array can have any dimensions when the array is created,you can define the
number of dimensions by using the ndim argumenṭ.

create an array with 5 dimensions and verify that it has 5 dimensions:

In [1]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print('number of dimension:', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimension: 5


get the element from the following array:

In [ ]:
arr = np.array([1,2,3,4])
print(arr[1])

2


get the third and sixth and 8th element from the following array and add them

In [ ]:
m = np.array([1,2,3,4,5,6,7,86,24,24,46,78])
print("the second element is",m[2])
print("the fifth element is",m[5])
print("the fourth element is",m[4])
print("the sum of element is",m[2]+m[5]+m[4])

the second element is 3
the fifth element is 6
the fourth element is 5
the sum of element is 14


acess 2d array

numpy array indexing

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5,6,6],[1,2,3,4,5,6,7]])
print('2nd element of 1st row:',arr[0,1])


2nd element of 1st row: 2


In [ ]:
arr = np.array([[87,22,19,354,56,3,443],[12,23,56,78,390,9,67]])
print('6th element of 2nd row:',arr[0,6])

6th element of 2nd row: 443


In [ ]:
arr = np.array([[1,2,3,4,5,6,6],[1,2,3,4,5,6,7]])
print('first element of this row:',arr[0,5])
print('last element of this row:',arr[1,4])
print("sum is",arr[0,5]+arr[1,4])

first element of this row: 6
last element of this row: 5
sum is 11


slicing of numpy arrays
joint
concatinate

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:5])

[3 4 5]


In [ ]:
arr = np.array([[1,34,56,78,9],[12,34,5,6,7]])
print(arr[0,1:5])

[34 56 78  9]


In [ ]:
arr =np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(arr[0,0:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print([arr.dtype])

[dtype('int64')]


In [ ]:
arr = np.array([1,2,3,4],dtype = 'i4')
print(arr)
print(arr.dtype)


[1 2 3 4]
int32


numpy shape of array

numpy shape of a

In [ ]:
import numpy as np

In [ ]:
arr =np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr.shape)

(2, 5)


In [ ]:
arr1 =np.array([4,5,6])
arr2 =np.array([7,8,9])
arr =np.concatenate((arr1,arr2))
print(arr)

[4 5 6 7 8 9]


In [ ]:
arr1 =np.array([[4,5],[6,9]])
arr2 = np.array([[6,7],[8,9]])
arr =np.concatenate((arr1,arr2))
print(arr)

[[4 5]
 [6 9]
 [6 7]
 [8 9]]


splitting numpy array

In [ ]:
arr = np.array([7,8,9,10])
newarr = np.array_split(arr,3)
print(newarr)

[array([7, 8]), array([9]), array([10])]


ravel and flatten

In [ ]:
#convert multidimentional array into 1 d array
m = np.array([[[1,2,3],[12,13,14],[223,34,56]]])
print(m)
print("dimension is ",m.ndim)
n = m.ravel()
print(n)
print("dimension is ",n.ndim)

[[[  1   2   3]
  [ 12  13  14]
  [223  34  56]]]
dimension is  3
[  1   2   3  12  13  14 223  34  56]
dimension is  1


In [ ]:
m = np.array([[[1,2,3],[12,13,14],[223,34,56]]])
print(m)
print("dimension is ",m.ndim)
n = m.flatten()
print(n)
print("dimension is ",n.ndim)

[[[  1   2   3]
  [ 12  13  14]
  [223  34  56]]]
dimension is  3
[  1   2   3  12  13  14 223  34  56]
dimension is  1


unique function

In [ ]:
k = np.array([12,23,24,25,26,27,27,26,252,25,24,23,24])
print(k)
x =np.unique(k)
print(x)


[ 12  23  24  25  26  27  27  26 252  25  24  23  24]
[ 12  23  24  25  26  27 252]


In [ ]:
k = np.array([12,23,24,25,26,27,27,26,252,25,24,23,24])
print(k)
x =np.unique(k, return_index = True , return_counts=True)
print(x)

[ 12  23  24  25  26  27  27  26 252  25  24  23  24]
(array([ 12,  23,  24,  25,  26,  27, 252]), array([0, 1, 2, 3, 4, 5, 8]), array([1, 2, 3, 2, 2, 2, 1]))


In [ ]:
import numpy as np
k = np.array([12,23,24,25,26,27,27,26,252,25,24,23,24])
d = np.delete(k,[23])
print(k)


IndexError: index 23 is out of bounds for axis 0 with size 13

In [ ]:
import pandas as pd

In [ ]:
pd.read_csv()